<?php
return array(
	//普通
    "site.index.index" => array("route" => "(/)", "use" => "site_index_controller@index"),
    "site.index.index_ptag" => array("route" => "get /@p:[0-9]{1,}(-@tag)", "use" => "site_index_controller@index@p@tag"),
    "site.index.captcha" => array("route" => "get|post /captcha/@salt", "use" => "site_index_controller@captcha@salt"),
    "site.index.upimg" => array("route" => "post /upimg", "use" => "site_index_controller@upimg"),
    "site.user.login" => array("route" => "get|post /login", "use" => "site_user_controller@login"),
    "site.user.register"=> array("route" => "get|post /register", "use" => "site_user_controller@register"),
    "site.user.logout"=> array("route" => "get|post /logout", "use" => "site_user_controller@logout"),
    "site.index.checkcaptcha" => array("route" => "get|post /checkcaptcha/@salt", "use" => "site_index_controller@checkcaptcha@salt"),
    "site.user.check_unique_email"=> array("route" => "get|post /check_unique_email", "use" => "site_user_controller@check_unique_email"),
    "site.user.check_unique_nickname"=> array("route" => "get|post /check_unique_nickname", "use" => "site_user_controller@check_unique_nickname"),
    "site.user.emailvalidate"=> array("route" => "get|post /emailvalidate/@token", "use" => "site_user_controller@emailvalidate@token"),
    "site.user.findpwd"=> array("route" => "get|post /findpwd", "use" => "site_user_controller@findpwd"),
    "site.user.setpwd"=> array("route" => "get|post /setpwd(/@token)", "use" => "site_user_controller@setpwd@token"),
    "site.user.setting.editpwd"=> array("route" => "get|post /editpwd", "use" => "site_user_controller@editpwd", "before" => "site_user_service@logined"),
    "site.index.add"=> array("route" => "get|post /add", "use" => "site_index_controller@add", "before" => "site_user_service@logined"),
    "site.index.parsemarkdown"=> array("route" => "get|post /parsemarkdown", "use" => "site_index_controller@parsemarkdown"),
    "site.index.tagsearch"=> array("route" => "get|post /tagsearch", "use" => "site_index_controller@tagsearch"),
    "site.index.indextagsearch"=> array("route" => "get|post /indextagsearch", "use" => "site_index_controller@indextagsearch"),
    "site.index.v"=> array("route" => "/v-@p-@id", "use" => "site_index_controller@v@p@id"),
    "site.index.vgood"=> array("route" => "/vgood-@id", "use" => "site_index_controller@vgood@id", "before" => "site_user_service@logined"),
    "site.index.vbad"=> array("route" => "/vbad-@id", "use" => "site_index_controller@vbad@id", "before" => "site_user_service@logined"),
    "site.index.deletev"=> array("route" => "/deletev-@id", "use" => "site_index_controller@deletev@id", "before" => "site_user_service@logined"),
    "site.index.editv"=> array("route" => "/editv-@id", "use" => "site_index_controller@editv@id", "before" => "site_user_service@logined"),
    "site.index.reply"=> array("route" => "/reply", "use" => "site_index_controller@reply", "before" => "site_user_service@logined"),
    "site.index.noticeRead"=> array("route" => "/noticeRead-@id", "use" => "site_index_controller@noticeRead@id", "before" => "site_user_service@logined"),
    "site.index.n"=> array("route" => "/n-@id", "use" => "site_index_controller@n@id"),
    "site.index.msg"=> array("route" => "/msg(-@p:[0-9]{1,})", "use" => "site_index_controller@msg@p", "before" => "site_user_service@logined"),
    "site.index.msgv"=> array("route" => "/msgv-@id-@p", "use" => "site_index_controller@msgv@id@p", "before" => "site_user_service@logined"),
    "site.index.msgdelete"=> array("route" => "/msgdelete-@id", "use" => "site_index_controller@msgdelete@id", "before" => "site_user_service@logined"),
    "site.index.msgv_post"=> array("route" => "POST /msgv", "use" => "site_index_controller@msgv", "before" => "site_user_service@logined"),
    "site.index.addmsg"=> array("route" => "/addmsg(-@id:[0-9]{1,})", "use" => "site_index_controller@addmsg@id", "before" => "site_user_service@logined"),
    "site.user.u"=> array("route" => "/u(-@id)", "use" => "site_user_controller@u@id"),
    "site.user.me"=> array("route" => "/me(-@p)", "use" => "site_user_controller@me@p", "before" => "site_user_service@logined"),
    "site.user.myreply"=> array("route" => "/myreply(-@p)", "use" => "site_user_controller@myreply@p", "before" => "site_user_service@logined"),
    "site.user.setting"=> array("route" => "/setting", "use" => "site_user_controller@setting", "before" => "site_user_service@logined"),
    "site.index.notice"=> array("route" => "/notice(-@p)", "use" => "site_index_controller@notice@p", "before" => "site_user_service@logined"),
    "site.index.usersearch"=> array("route" => "/usersearch", "use" => "site_index_controller@usersearch"),
    "site.index.t"=> array("route" => "/t-@p-@tag", "use" => "site_index_controller@t@p@tag"),
    "site.index.stag"=> array("route" => "/stag", "use" => "site_index_controller@stag"),
    "site.index.setTop"=> array("route" => "/setTop/@id", "use" => "site_index_controller@setTop@id", "before" => "site_user_service@logined"),
    "site.index.delReply"=> array("route" => "/delReply/@id/@arcId", "use" => "site_index_controller@delReply@id@arcId", "before" => "site_user_service@logined"),
    //后台
    "admin.index.index"=>array("route" => "/admin", "use" => "admin_index_controller@index", "before" => "admin_index_service@checklogin"),
    "admin.user.login"=>array("route" => "/admin/login", "use" => "admin_user_controller@login"),
    "admin.user.logout"=>array("route" => "/admin/logout", "use" => "admin_user_controller@logout"),
    "admin.user.tagssearch"=>array("route" => "get|post /admin/user/tagssearch", "use" => "admin_user_controller@tagssearch"),
    //用户管理
    "admin.rbac.member"=>array("route" => "/admin/member", "use" => "admin_rbac_controller@member", "before" => "admin_index_service@checklogin","name"=>"后台用户查看","group_name"=>"后台用户管理"),
    "admin.rbac.member.add"=>array("route" => "get|post /admin/member/add", "use" => "admin_rbac_controller@memberAdd", "before" => "admin_index_service@checklogin","name"=>"后台用户添加","group_name"=>"后台用户管理"),
    "admin.rbac.member.edit"=>array("route" => "get|post /admin/member/edit(/@id)", "use" => "admin_rbac_controller@memberEdit@id", "before" => "admin_index_service@checklogin","name"=>"后台用户编辑","group_name"=>"后台用户管理"),
    "admin.rbac.member.delete"=>array("route" => "get|post /admin/member/delete/@id", "use" => "admin_rbac_controller@memberDelete@id", "before" => "admin_index_service@checklogin","name"=>"后台用户删除","group_name"=>"后台用户管理"),
    //节点管理
    "admin.rbac.node"=>array("route" => "/admin/node", "use" => "admin_rbac_controller@node", "before" => "admin_index_service@checklogin","name"=>"节点查看","group_name"=>"节点管理"),

    //部门管理
    "admin.rbac.dept"=>array("route" => "get|post /admin/dept(/@p)", "use" => "admin_rbac_controller@dept@p", "before" => "admin_index_service@checklogin","name"=>"部门查看","group_name"=>"部门管理"),
    "admin.rbac.dept.add"=>array("route" => "get|post /admin/dept/add(/@pid)", "use" => "admin_rbac_controller@deptAdd@pid", "before" => "admin_index_service@checklogin","name"=>"部门添加","group_name"=>"部门管理"),
    "admin.rbac.dept.edit"=>array("route" => "get|post /admin/dept/edit(/@id)", "use" => "admin_rbac_controller@deptEdit@id", "before" => "admin_index_service@checklogin","name"=>"部门编辑","group_name"=>"部门管理"),
    "admin.rbac.dept.delete"=>array("route" => "get|post /admin/dept/delete(/@id)", "use" => "admin_rbac_controller@deptDelete@id", "before" => "admin_index_service@checklogin","name"=>"部门删除","group_name"=>"部门管理"),
    //权限管理
    "admin.rbac.access"=>array("route" => "get|post /admin/access", "use" => "admin_rbac_controller@access", "before" => "admin_index_service@checklogin","name"=>"职位查看","group_name"=>"权限/职位管理"),
    "admin.rbac.access.add"=>array("route" => "get|post /admin/access/add", "use" => "admin_rbac_controller@accessAdd", "before" => "admin_index_service@checklogin","name"=>"职位添加","group_name"=>"权限/职位管理"),
    "admin.rbac.access.edit"=>array("route" => "get|post /admin/access/edit(/@id)", "use" => "admin_rbac_controller@accessEdit@id", "before" => "admin_index_service@checklogin","name"=>"职位编辑","group_name"=>"权限/职位管理"),
    "admin.rbac.access.delete"=>array("route" => "get|post /admin/access/delete/@id", "use" => "admin_rbac_controller@accessDelete@id", "before" => "admin_index_service@checklogin","name"=>"职位删除","group_name"=>"权限/职位管理"),
    "admin.rbac.access.get"=>array("route" => "/admin/access/get/@id", "use" => "admin_rbac_controller@accessGet@id", "before" => "admin_index_service@checklogin"),
    //配置管理
    "admin.setting.index"=>array("route" => "get|post /admin/setting(/index)", "use" => "admin_setting_controller@index", "before" => "admin_index_service@checklogin","name"=>"配置管理","group_name"=>"配置管理"),
    "admin.setting.cache"=>array("route" => "get|post /admin/setting/cache", "use" => "admin_setting_controller@cache", "before" => "admin_index_service@checklogin","name"=>"缓存管理","group_name"=>"配置管理"),
    //网站管理
    "admin.index.notice"=>array("route" => "get|post /admin/notice", "use" => "admin_index_controller@notice", "before" => "admin_index_service@checklogin","name"=>"公告管理","group_name"=>"公告管理"),
    "admin.index.notice.add"=>array("route" => "get|post /admin/notice/add", "use" => "admin_index_controller@notice_add", "before" => "admin_index_service@checklogin","name"=>"添加公告","group_name"=>"公告管理"),
    "admin.index.notice.edit"=>array("route" => "get|post /admin/notice/edit/@id", "use" => "admin_index_controller@notice_edit@id", "before" => "admin_index_service@checklogin","name"=>"编辑公告","group_name"=>"公告管理"),
    "admin.index.notice.delete"=>array("route" => "get|post /admin/notice/delete/@id", "use" => "admin_index_controller@notice_delete@id", "before" => "admin_index_service@checklogin","name"=>"删除公告","group_name"=>"公告管理"),
    //导航管理
    "admin.site.menu"=>array("route" => "get|post /admin/menu", "use" => "admin_site_controller@menu", "before" => "admin_index_service@checklogin","name"=>"导航管理","group_name"=>"导航管理"),
    "admin.site.menu.add"=>array("route" => "get|post /admin/menu_add", "use" => "admin_site_controller@menu_add", "before" => "admin_index_service@checklogin","name"=>"添加导航","group_name"=>"导航管理"),
    "admin.site.menu.edit"=>array("route" => "get|post /admin/menu_edit/@id", "use" => "admin_site_controller@menu_edit@id", "before" => "admin_index_service@checklogin","name"=>"编辑导航","group_name"=>""),
    "admin.site.menu.delete"=>array("route" => "get|post /admin/menu_delete/@id", "use" => "admin_site_controller@menu_delete@id", "before" => "admin_index_service@checklogin","name"=>"删除导航","group_name"=>"导航管理"),
    //主题管理
    "admin.site.arc"=>array("route" => "get|post /admin/arc", "use" => "admin_site_controller@arc", "before" => "admin_index_service@checklogin","name"=>"主题管理","group_name"=>"主题管理"),
    "admin.site.arc.delete"=>array("route" => "get|post /admin/arc_delete/@id", "use" => "admin_site_controller@arc_delete@id", "before" => "admin_index_service@checklogin","name"=>"屏蔽主题","group_name"=>"主题管理"),
    //会员管理
    "admin.site.user"=>array("route" => "get|post /admin/user", "use" => "admin_site_controller@user", "before" => "admin_index_service@checklogin","name"=>"会员管理","group_name"=>"会员管理"),
    "admin.site.setLevel"=>array("route" => "get|post /admin/user/setLevel/@uid", "use" => "admin_site_controller@setLevel@uid", "before" => "admin_index_service@checklogin","name"=>"设为网站管理员","group_name"=>"会员管理"),
);